### ISSUE TITLE
Please provide download for module itself as a release

### ISSUE THREAD

**Issue by artisticcheese** [theonlyway/xDSCFirewall#27]
Azure ARM Automation account module template expect URI parameter for module as described here (https://docs.microsoft.com/en-us/azure/templates/microsoft.automation/automationaccounts/modules#ContentLink), it's impossible to import from Gallery. Please add a ZIP file containing DSC resource to releases so it can be used in Azure Automation.

**Comment by theonlyway** [comment]
Interesting. I haven't used that before so where do you need the release to be located? Do you mean the releases on this repo? If so there should already be a release that has a zip with the content (https://github.com/theonlyway/xDSCFirewall/releases/tag/1.6.21). Is the structure of the release incorrect?

On the flip side the functionality of this module has been merged in to the one provided by Microsoft as per this pull request https://github.com/PowerShell/xNetworking/pull/257 so it may give you the functionality you are after since it's managed by Microsoft it should already be compliant with Azure Automation (hopefully)

**Comment by artisticcheese** [comment]
If it's merged into xNetworking then nothing is needed, we are good, thanks.
